version: "3.6"
services:
  manuskript:
    command:
      - "/bin/sh"
      - "-c"
      - "/usr/bin/manuskript"
    environment:
      - name=value
      - DISPLAY=$DISPLAY
      - WAYLAND_DISPLAY=$WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      - PULSE_SERVER=$PULSE_SERVER
    image: "manuskriptdocker:latest"
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    user: "manuskript-user"
    volumes:
      - "/mnt/c/manuskript-docker/books:/home/manuskript-user/books"
      - "/mnt/wslg:/mnt/wslg"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
